### ISSUE TITLE
App crash while record video in some devices

### ISSUE THREAD

**Issue by jignesh8992** [uestccokey/EZFilter#40]
AndroidRuntime: FATAL EXCEPTION: MediaVideoEncoder
                                                                   Process: asha.glich.effect, PID: 19849
                                                                   java.lang.IllegalStateException
                                                                       at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                                                       at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2392)
                                                                       at cn.ezandroid.ezfilter.media.record.MediaEncoder.drain(MediaEncoder.java:223)
                                                                       at cn.ezandroid.ezfilter.media.record.MediaEncoder.run(MediaEncoder.java:105)
                                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by uestccokey** [comment]
Which version do you use?
try new version 2.0.8
